spack:
  view: true
  strip: false
  packages:
    all:
      target: [x86_64]
  config:
    compiler:
      target: x86_64
    install_missing_compilers: true
    install_tree:
      root: /opt/software
      padded_length: 512
  container:
    strip: true
    os_packages:
      build:
        - python3-boto3
  mirrors:
    autamus: s3://sandbox-cache
    secondary: s3://autamus-cache
