spack:
  view: true
  packages:
    all:
      target: [x86_64]
  config:
    compiler:
      target: x86_64
    install_missing_compilers: true
    install_tree: /opt/software/I_think_I_can_I_think_I_can_I_think_I_can
  container:
    strip: true
    os_packages:
      build:
        - python3-boto3
  mirrors:
    autamus: s3://sandbox-cache
    secondary: s3://autamus-cache